### ISSUE TITLE
Stop command for maestro required

### ISSUE THREAD

**Issue by deepikabhavnani** [armPelionEdge/meta-pelion-edge#83]
Stop command for maestro required
https://github.com/armPelionEdge/meta-pelion-edge/blob/master/recipes-wigwag/maestro/maestro/maestro.sh#L29

opkg install / restart of maestro results in multiple processes running for maestro

**Comment by theotherjimmy** [comment]
It's actually there, but it stops something called `DeviceJS` when I last checked.

**Comment by deepikabhavnani** [comment]
> It's actually there, but it stops something called DeviceJS when I last checked.

It does not kill Maestro - DevieJS is the child process created by maestro. Everything else is stopped and started, but we end up with 2 processes of maestro.. Confirmed with `ps -aux | grep maestro`

**Comment by theotherjimmy** [comment]
Oh my. This should be pretty easy to fix. Or we could go to systemd for this, it handles daemon processes pretty well.

**Comment by cmonr** [comment]
> This should be pretty easy to fix.

So many things to improve, so little time :sweat_smile:

**Comment by theotherjimmy** [comment]
#86 Should have made this irrelevant, as the init script is no longer used.
